### ISSUE TITLE
Installer failing to download package libsigc++-2.0-0c2a

### ISSUE THREAD

**Issue by gitbisector** [zfsonlinux/debian-installers#1]
![image2015-4-11 20-5-20](https://cloud.githubusercontent.com/assets/7624946/7104289/e9e28c42-e089-11e4-943a-b2cc1d33805e.png)

...
Apr 12 03:19:41 main-menu[1139]: DEBUG: resolver (libc6-udeb): package doesn't exist (ignored)
Apr 12 03:19:42 main-menu[1139]: INFO: Menu item 'choose-mirror' selected
Apr 12 03:19:42 anna-install: Queueing udeb apt-mirror-setup for later installation
Apr 12 03:19:43 choose-mirror[2567]: DEBUG: command: wget -q http://archive.zfsonlinux.org/debian/dists/oldstable/Release -O - | grep -E '^(Suite|Codename):'
Apr 12 03:19:43 choose-mirror[2567]: DEBUG: command: wget -q http://archive.zfsonlinux.org/debian/dists/stable/Release -O - | grep -E '^(Suite|Codename):'
Apr 12 03:19:43 choose-mirror[2567]: DEBUG: command: wget -q http://archive.zfsonlinux.org/debian/dists/testing/Release -O - | grep -E '^(Suite|Codename):'
Apr 12 03:19:44 choose-mirror[2567]: DEBUG: command: wget -q http://archive.zfsonlinux.org/debian/dists/unstable/Release -O - | grep -E '^(Suite|Codename):'
Apr 12 03:19:44 choose-mirror[2567]: INFO: mirror does not have any suite symlinks
Apr 12 03:19:44 choose-mirror[2567]: DEBUG: command: wget -q http://archive.zfsonlinux.org/debian/dists/wheezy/Release -O - | grep -E '^(Suite|Codename):'
Apr 12 03:19:44 choose-mirror[2567]: DEBUG: command: wget -q http://archive.zfsonlinux.org/debian/dists/stable/Release -O - | grep -E '^(Suite|Codename):'
Apr 12 03:19:45 choose-mirror[2567]: INFO: suite/codename set to: wheezy/wheezy
Apr 12 03:19:45 choose-mirror[2567]: DEBUG: command: wget -q http://archive.zfsonlinux.org/debian/dists/wheezy/main/binary-amd64/Release -O - | grep ^Architecture:
Apr 12 03:19:45 anna-install: Queueing udeb wheezy-support for later installation
Apr 12 03:19:45 main-menu[1139]: (process:2560): wget: server returned error: HTTP/1.1 404 Not Found
Apr 12 03:19:45 main-menu[1139]: (process:2560): wget: server returned error: HTTP/1.1 404 Not Found
Apr 12 03:19:45 main-menu[1139]: (process:2560): wget: server returned error: HTTP/1.1 404 Not Found
Apr 12 03:19:45 main-menu[1139]: (process:2560): wget: server returned error: HTTP/1.1 404 Not Found
Apr 12 03:19:45 main-menu[1139]: (process:2560): wget: server returned error: HTTP/1.1 404 Not Found
Apr 12 03:19:45 main-menu[1139]: DEBUG: resolver (libc6-udeb): package doesn't exist (ignored)
Apr 12 03:19:45 main-menu[1139]: INFO: Menu item 'download-installer' selected
Apr 12 03:19:45 net-retriever: Not verifying Release signature: unauthenticated mode enabled
Apr 12 03:19:46 anna[2622]: DEBUG: resolver (ufsutils-udeb): package doesn't exist (ignored)
Apr 12 03:19:46 anna[2622]: DEBUG: resolver (ufsutils-udeb): package doesn't exist (ignored)
Apr 12 03:19:46 anna[2622]: DEBUG: retrieving apt-mirror-setup 1:0.79
Apr 12 03:19:47 anna[2622]: DEBUG: retrieving apt-setup-udeb 1:0.79
Apr 12 03:19:47 anna[2622]: DEBUG: retrieving ata-modules-3.2.0-4-amd64-di 3.2.63-2
Apr 12 03:19:48 anna[2622]: DEBUG: retrieving base-installer 1.151.ZOL1

Full syslog is here: https://gist.github.com/gitbisector/06fe1692d48a917880de

**Comment by FransUrbo** [comment]
It's those DARN '+' in filenames! S3 can't handle them, so I have to make links. Hardlinks for files, and I THOUGHT a symlink locally would translate as a hardlink remotly. But apparently not. Got do do a copy.
